services:
  backup:
    image: jyasapara/garrison:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - BACKUP_CONTAINER_VOLUMES=restic_cache:/cache
      - RESTIC_REPOSITORY=$RESTIC_REPOSITORY
      - RESTIC_PASSWORD=$RESTIC_PASSWORD
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - BACKUP_CONTAINER_COMMAND=--cache-dir /cache -q --json backup -H {server_name}:{project_name}:{container_name} --tag garrison --tag {volume_name} {volume_path}
      - BACKUP_CONTAINER_IMAGE=restic/restic
